import { prisma } from "@/lib/prisma";
import { getOrSet, delPattern } from "@/lib/cache";

/**
 * Warms up the search cache for quick product search functionality.
 * This runs on app startup and whenever a product is created, updated, or deleted.
 * It deletes existing product list cache keys and pre-loads all pages with limit=250.
 */
export async function warmUpSearchCache() {
  try {
    console.log("[cache-warmup] Starting search cache warm-up...");

    // First, count total active products
    const total = await prisma.product.count({
      where: { isActive: true, isDeleted: false },
    });

    const limitNum = 250;
    const pages = Math.ceil(total / limitNum) || 1;

    console.log(`[cache-warmup] Found ${total} active products. Pre-loading ${pages} page(s) of size ${limitNum}...`);

    for (let pageNum = 1; pageNum <= pages; pageNum++) {
      const skip = (pageNum - 1) * limitNum;
      
      // Query database directly
      const products = await prisma.product.findMany({
        where: { isActive: true, isDeleted: false },
        include: {
          category: true,
          variants: true,
          images: {
            select: {
              id: true,
            },
            orderBy: {
              createdAt: "asc",
            },
          },
        },
        orderBy: { name: "asc" },
        skip,
        take: limitNum,
      });

      const data = {
        products,
        pagination: {
          page: pageNum,
          limit: limitNum,
          total,
          pages,
        },
      };

      // Construct the exact cache key generated by buildListCacheKey for these params
      // cat=|feat=|q=|p=X|l=250|min=|max=|sort=name_asc
      const cacheKey = `products:list:cat=|feat=|q=|p=${pageNum}|l=${limitNum}|min=|max=|sort=name_asc`;

      // Set directly in Redis with a 24-hour TTL (86400 seconds)
      await getOrSet(cacheKey, 86400, async () => data);
      console.log(`[cache-warmup] Successfully cached page ${pageNum}/${pages} to key: ${cacheKey}`);
    }

    console.log("[cache-warmup] Search cache warm-up complete.");
  } catch (error) {
    console.error("[cache-warmup] Failed to warm up search cache:", error);
  }
}
